spring.datasource.url=jdbc:postgresql://localhost:5432/TaxiCamino
spring.datasource.username=postgres
spring.datasource.password=Ez8w7!!K

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public   

spring.mail.host=smtp.gmail.com
spring.mail.username=darioxx.fs@gmail.com
spring.mail.password=Dario987

jwt.secret=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
jwt.expirationMs=21600

server.port=8080
